In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn 
import process_fns as pfns
import pdm_functions as fns
import torch


In [2]:
data = pfns.to_stack('dataset/5528_droped_data.csv', 'cls') 

In [37]:
X_train, y_train = data[0][0], data[0][1]
X_test, y_test = data[1][0], data[1][1]
X_dev, y_dev = data[2][0], data[2][1]

In [38]:
# X_dev.shape, y_dev.shape
X_test.shape, y_test.shape

(torch.Size([444, 3, 2048]), torch.Size([444]))

In [39]:
y_train

tensor([1, 1, 1,  ..., 0, 0, 0])

In [40]:
len(y_train[y_train == 1]), len(y_train[y_train != 1])

(1332, 120)

In [41]:
y_train[-120:]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
y_train[:1332]

tensor([1, 1, 1,  ..., 1, 1, 1])

In [43]:
y_train_pos = y_train[:1332]
y_train_neg = y_train[-120:]

In [44]:
X_train_pos = X_train[:1332]
X_train_neg = X_train[-120:]


In [45]:
X_train_pos.shape, X_train_neg.shape

(torch.Size([1332, 3, 2048]), torch.Size([120, 3, 2048]))

In [48]:
X_train_pos = X_train_pos.reshape(111, 1, 36, 2048)
X_train_neg = X_train_neg.reshape(10, 1, 36, 2048)

In [49]:
X_train_neg = fns.multi_datasets_stacks(X_train_neg, multi_dim= 10, num_groups= 12)

100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 257.51it/s]


In [59]:
X_train_neg.shape, X_train_pos.shape

(torch.Size([100, 1, 36, 2048]), torch.Size([111, 1, 36, 2048]))

In [54]:
y_train_neg = y_train_neg.repeat(10)

In [58]:
y_train_pos.shape, y_train_neg.shape

(torch.Size([1332]), torch.Size([1200]))

In [60]:
y_train_pos = y_train_pos.reshape(111, 12)
y_train_neg = y_train_neg.reshape(100, 12)

In [61]:
y_train_pos= torch.tensor([y_train_pos[i][0].item() for i in range(y_train_pos.shape[0])])
y_train_neg= torch.tensor([y_train_neg[i][0].item() for i in range(y_train_neg.shape[0])])
# y_train_pos.shape, y_train_neg.shape

In [62]:
X_train_pos.shape, y_train_pos.shape, X_train_neg.shape, y_train_neg.shape

(torch.Size([111, 1, 36, 2048]),
 torch.Size([111]),
 torch.Size([100, 1, 36, 2048]),
 torch.Size([100]))

In [64]:
X_train = torch.concat((X_train_pos, X_train_neg), dim=0)
y_train = torch.concat((y_train_pos, y_train_neg), dim=0)
X_train.shape, y_train.shape

(torch.Size([211, 1, 36, 2048]), torch.Size([211]))

In [65]:
X_train_for_model_structure = fns.multi_datasets_stacks(X_train, multi_dim= 25, num_groups=12)
y_train_for_model_structure = y_train.repeat(25)
X_train_for_model_structure.shape, y_train_for_model_structure.shape

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 60.27it/s]


(torch.Size([5275, 1, 36, 2048]), torch.Size([5275]))

In [66]:
file_path = 'dataset/train_datasets/train_set_for_model_structure.pt'

torch.save({'X_train_for_model_structure': X_train_for_model_structure, 'y_train_for_model_structure': y_train_for_model_structure}, file_path)

In [67]:
train_for_model_structure = torch.load(file_path)

C:\Users\user\AppData\Local\Temp\ipykernel_10100\2435021694.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  train_for_model_structure = torch.load(file_path)


In [70]:
check_y = train_for_model_structure['y_train_for_model_structure']

In [73]:
len(check_y[check_y == 1]), len(check_y[check_y != 1])

(2775, 2500)

In [18]:
# y_train = y_train.reshape(121,12)
# y_dev = y_dev.reshape(37, 12)
y_test = y_test.reshape(37, 12)

In [20]:
# y_train.shape
y_test.shape

torch.Size([37, 12])

In [8]:
# y_train
y_dev

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1

In [21]:
# y_train = torch.tensor([y_train[i][0].item() for i in range(y_train.shape[0])])
# y_dev = torch.tensor([y_dev[i][0].item() for i in range(y_dev.shape[0])])
y_test = torch.tensor([y_test[i][0].item() for i in range(y_test.shape[0])])

In [24]:
# y_train.shape
y_test.shape

torch.Size([37])

In [29]:
# X_train_grouped = X_train.reshape(121, 1, 36, 2048)
# X_dev_grouped = X_dev.reshape(37, 1, 36, 2048)
X_test_grouped = X_test.reshape(37, 1, 36, 2048)

In [12]:
# X_train_grouped.shape
X_dev_grouped.shape

torch.Size([37, 1, 36, 2048])

In [13]:
len(y_dev[y_dev == 1]), len(y_dev[y_dev !=1])

(34, 3)

In [13]:
# X_train_grouped.shape[0]

num_dates = X_train_grouped.shape[0]
num_rows = X_train_grouped[0][0].shape[0]
num_groups = 12
num_features = X_train_grouped[0][0][0].shape[0]


grouped_tensor = X_train_grouped.view(num_dates, 1 ,num_groups, int(num_rows/num_groups), -1)

# grouped_tensor.shape

permuted_indices = fns.get_random_permutation(12)
permuted_tensor = grouped_tensor[:, :, permuted_indices, :, :]

print(permuted_indices)



tensor([ 5,  8,  4,  0, 11,  3,  9, 10,  6,  7,  2,  1])


In [14]:
# permuted_tensor.shape

# grouped_tensor.shape

grouped_tensor[2][0][7]

# permuted_tensor.shape[1]

tensor([[2.4994e-04, 4.5668e-04, 6.2867e-04,  ..., 4.0409e-04, 1.5007e-04,
         1.5202e-04],
        [1.8990e-04, 1.7246e-04, 1.9197e-04,  ..., 4.3522e-04, 3.7189e-04,
         1.0465e-04],
        [7.9423e-05, 2.4039e-04, 3.9576e-04,  ..., 1.5194e-04, 8.5624e-05,
         2.2916e-04]])

In [15]:
permuted_tensor[2][0][0]

tensor([[3.7633e-04, 4.0001e-04, 1.9710e-04,  ..., 4.6099e-04, 4.9943e-04,
         4.5972e-04],
        [4.4028e-04, 1.9330e-04, 3.5636e-04,  ..., 1.6474e-04, 2.5121e-04,
         1.7059e-05],
        [1.8912e-04, 1.6558e-04, 1.0677e-04,  ..., 2.9551e-04, 4.3159e-04,
         3.7920e-04]])

In [16]:
# def multi_datasets_stacks(df, multi_dim, num_groups): 
#     permuted_tensors_list = []
#     num_dates = df.shape[0]
#     num_rows = df[0][0].shape[0]
#     num_features = df[0][0][0].shape[0]
#     grouped_tensor = df.view(num_dates, 1 ,num_groups, int(num_rows/num_groups), -1)

#     for _ in range(multi_dim): 
#         permuted_indices = fns.get_random_permutation(12)
#         permuted_tensor = grouped_tensor[:, :, permuted_indices, :, :]
        
#         permuted_tensors_list.append(permuted_tensor)

#     stacked_tensor = torch.cat(permuted_tensors_list, dim=0)
#     final_tensor = stacked_tensor.view(-1, 1, num_rows, num_features)

#     return final_tensor

In [17]:
# a = multi_datasets(X_train_grouped, 4, 12)

In [18]:
# a.shape

In [19]:
# permuted_indices = fns.get_random_permutation(12)
# permuted_indices

## Multiplying Stacked Data

In [20]:
X_train_aug = fns.multi_datasets_stacks(X_train_grouped, multi_dim=100, num_groups=12)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 95.05it/s]


In [21]:
y_train_aug = y_train.repeat(500)

In [27]:
# X_train_aug.shape, y_train_aug.shape
X_dev_grouped.shape, y_dev.shape

(torch.Size([37, 1, 36, 2048]), torch.Size([37]))

In [30]:
# # file_path = 'dataset/train_datasets/train_data_stacked.pkl'
# # with open (file_path, 'wb') as f:
#     # pickle.dump({'X_train_stacked': X_train_aug, 'y_train_stacked': y_train_aug}, f)

# file_path = 'dataset/train_datasets/train_data_stacked.pkl'

# torch.save({'X_train_stacked': X_train_aug, 'y_train_stacked': y_train_aug}, file_path)


# file_path = 'dataset/train_datasets/dev_data_stacked.pt'

# torch.save({'X_dev_stacked': X_dev_grouped, 'y_dev_stacked': y_dev}, file_path)

file_path = 'dataset/train_datasets/test_data_stacked.pt'

torch.save({'X_test_stacked': X_test_grouped, 'y_test_stacked': y_test}, file_path)